import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Typography } from '../../theme/typography';
import { Spacing, Radius } from '../../theme/spacing';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgDeep,
  },
  header: {
    paddingTop: 56,
    paddingHorizontal: Spacing.lg,
    paddingBottom: Spacing.sm,
    backgroundColor: 'rgba(14,31,23,0.95)',
    borderBottomWidth: 1,
    borderColor: Colors.border,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backBtnText: {
    color: Colors.textSecondary,
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.semiBold,
  },
  content: {
    padding: Spacing.lg,
    paddingBottom: Spacing.huge,
  },
  heroBanner: {
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: 'rgba(19,42,28,0.9)',
    padding: Spacing.xl,
    marginBottom: Spacing.xl,
  },
  heroBadge: {
    borderWidth: 1,
    borderColor: 'rgba(201,138,60,0.4)',
    backgroundColor: 'rgba(201,138,60,0.15)',
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm + 2,
    paddingVertical: Spacing.xs + 1,
    alignSelf: 'flex-start',
    marginBottom: Spacing.md,
  },
  heroBadgeText: {
    color: Colors.gold,
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.extraBold,
    textTransform: 'uppercase',
    letterSpacing: Typography.letterSpacing.wide,
  },
  heroTitle: {
    fontSize: Typography.fontSize.xxl,
    fontWeight: Typography.fontWeight.extraBold,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  heroSubtitle: {
    fontSize: Typography.fontSize.base - 1,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  sectionLabel: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: Typography.letterSpacing.wide,
    marginBottom: Spacing.sm + 2,
  },
  presetsRow: {
    gap: Spacing.sm,
    marginBottom: Spacing.xl,
  },
  presetBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: 'rgba(19,42,28,0.8)',
    borderRadius: Radius.lg,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  presetBtnText: {
    color: Colors.textPrimary,
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.semiBold,
  },
  presetLoad: {
    color: Colors.gold,
    fontSize: Typography.fontSize.xs - 1,
    fontWeight: Typography.fontWeight.extraBold,
    letterSpacing: Typography.letterSpacing.wide,
  },
  card: {
    backgroundColor: 'rgba(19,42,28,0.92)',
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.lg + 2,
    marginBottom: Spacing.lg,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.lg,
    borderBottomWidth: 1,
    borderColor: Colors.border,
    paddingBottom: Spacing.base,
  },
  cardTitle: {
    fontSize: Typography.fontSize.lg,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
    flex: 1,
  },
  resetBtn: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm + 2,
    paddingVertical: Spacing.xs + 2,
  },
  resetBtnText: {
    color: Colors.textMuted,
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.semiBold,
  },
  errorBanner: {
    borderRadius: Radius.base || Radius.md,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.4)',
    backgroundColor: 'rgba(127,0,0,0.3)',
    padding: Spacing.md,
    marginBottom: Spacing.lg,
  },
  errorBannerText: {
    color: '#fca5a5',
    fontSize: Typography.fontSize.sm,
  },
  fieldBlock: {
    marginBottom: Spacing.lg,
  },
  fieldHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: Spacing.sm,
  },
  fieldLabel: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: '#D3E0D0',
  },
  fieldRange: {
    fontSize: Typography.fontSize.xs,
    color: 'rgba(138,166,143,0.8)',
  },
  binaryRow: {
    flexDirection: 'row',
    gap: Spacing.sm + 2,
  },
  binaryBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingVertical: Spacing.sm + 2,
    alignItems: 'center',
    backgroundColor: Colors.bgDeep,
  },
  binaryBtnActive: {
    borderColor: Colors.greenBright,
    backgroundColor: 'rgba(56,224,123,0.15)',
  },
  binaryBtnText: {
    color: Colors.textMuted,
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
  },
  binaryBtnTextActive: {
    color: Colors.greenBright,
  },
  numInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  numInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm + 2,
    fontSize: Typography.fontSize.base,
    color: Colors.textPrimary,
    backgroundColor: Colors.bgDeep,
  },
  unitLabel: {
    position: 'absolute',
    right: Spacing.md,
    color: Colors.textMuted,
    fontSize: Typography.fontSize.sm,
  },
  predictBtn: {
    marginTop: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: Colors.greenBright,
    paddingVertical: Spacing.lg,
    alignItems: 'center',
  },
  predictBtnDisabled: {
    opacity: 0.5,
  },
  predictBtnText: {
    color: '#09170E',
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.extraBold,
  },
  resultCard: {
    borderWidth: 1,
  },
  resultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: Spacing.md,
  },
  resultHeaderLabel: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    textTransform: 'uppercase',
    letterSpacing: Typography.letterSpacing.wide,
    color: 'rgba(255,255,255,0.6)',
  },
  riskBadge: {
    borderRadius: Radius.xl,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
  },
  riskBadgeText: {
    color: '#000',
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.extraBold,
    textTransform: 'uppercase',
    letterSpacing: Typography.letterSpacing.wide,
  },
  riskLevelText: {
    fontSize: Typography.fontSize.h1 - 2,
    fontWeight: Typography.fontWeight.extraBold,
    marginBottom: Spacing.lg,
    letterSpacing: Typography.letterSpacing.tight,
  },
  recommendationCard: {
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: 'rgba(14,31,23,0.6)',
    padding: Spacing.base,
    marginBottom: Spacing.md,
  },
  recommendationLabel: {
    fontSize: Typography.fontSize.xs,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.greenBright,
    marginBottom: Spacing.xs + 2,
    textTransform: 'uppercase',
  },
  recommendationText: {
    fontSize: Typography.fontSize.sm,
    color: '#D3E0D0',
    lineHeight: 18,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaLabel: {
    fontSize: Typography.fontSize.xs,
    color: Colors.textMuted,
  },
  metaValue: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.semiBold,
    color: Colors.textPrimary,
  },
  protocolNote: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.bgDeep,
    padding: Spacing.lg,
    marginBottom: Spacing.xl,
  },
  protocolTitle: {
    fontSize: Typography.fontSize.base - 1,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
    marginBottom: Spacing.sm,
  },
  protocolText: {
    fontSize: Typography.fontSize.xs,
    color: Colors.textMuted,
    lineHeight: 18,
  },
});
