import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Typography } from '../../theme/typography';
import { Spacing, Radius } from '../../theme/spacing';

export const styles = StyleSheet.create({
  chatContainer: {
    flex: 1,
    backgroundColor: '#0d1f17',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm + 2,
    padding: Spacing.lg,
    borderBottomWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(19,40,30,0.95)',
  },
  chatHeaderIcon: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm + 2,
    backgroundColor: Colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatHeaderIconText: {
    color: '#102419',
    fontSize: Typography.fontSize.lg,
    fontWeight: Typography.fontWeight.bold,
  },
  chatHeaderInfo: {
    flex: 1,
  },
  chatHeaderTitle: {
    fontSize: Typography.fontSize.base,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
  },
  chatHeaderStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs + 1,
    marginTop: Spacing.xxs,
  },
  chatStatusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Colors.greenNeon,
  },
  chatStatusText: {
    fontSize: Typography.fontSize.xs,
    color: Colors.goldLight,
  },
  clearHint: {
    fontSize: Typography.fontSize.xs,
    color: Colors.goldLight,
  },
  clearBtn: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  clearBtnActive: {
    backgroundColor: Colors.gold,
  },
  clearBtnText: {
    fontSize: Typography.fontSize.lg,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xxl,
  },
  emptyIcon: {
    width: 60,
    height: 60,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: '#162D21',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: Spacing.lg,
  },
  emptyIconText: {
    fontSize: Typography.fontSize.h2 - 2,
    color: Colors.gold,
  },
  emptyTitle: {
    fontSize: Typography.fontSize.xl,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
    textAlign: 'center',
    marginBottom: Spacing.sm,
  },
  emptySubtitle: {
    fontSize: Typography.fontSize.base - 1,
    color: Colors.textMuted,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: Spacing.xxl,
    maxWidth: 320,
  },
  promptGrid: {
    gap: Spacing.sm + 2,
    width: '100%',
  },
  promptChip: {
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(20,42,30,0.8)',
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.md,
  },
  promptChipText: {
    fontSize: Typography.fontSize.base - 1,
    fontWeight: Typography.fontWeight.medium,
    color: '#C2D8C6',
  },
  messageList: {
    padding: Spacing.lg,
    gap: Spacing.md,
  },
  bubbleRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: Spacing.sm,
    marginBottom: Spacing.sm + 2,
  },
  bubbleRowUser: {
    justifyContent: 'flex-end',
  },
  bubbleRowAI: {
    justifyContent: 'flex-start',
  },
  aiBotIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: Colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  aiBotIconText: {
    color: '#102419',
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
  },
  bubble: {
    maxWidth: '80%',
    borderRadius: Radius.xl - 2,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm + 2,
  },
  bubbleUser: {
    backgroundColor: Colors.gold,
    borderBottomRightRadius: Radius.xs,
  },
  bubbleAI: {
    backgroundColor: '#152B1F',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderBottomLeftRadius: Radius.xs,
  },
  bubbleText: {
    fontSize: Typography.fontSize.base,
    lineHeight: 20,
  },
  bubbleTextUser: {
    color: '#102419',
    fontWeight: Typography.fontWeight.medium,
  },
  bubbleTextAI: {
    color: Colors.textPrimary,
  },
  bubbleVoice: {
    fontSize: Typography.fontSize.xs - 1,
    color: Colors.textMuted,
    marginTop: Spacing.xs,
  },
  bubbleVoiceUser: {
    color: 'rgba(16,36,25,0.6)',
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.xs + 1,
    paddingVertical: Spacing.base,
  },
  typingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.gold,
  },
  errorBanner: {
    margin: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.3)',
    backgroundColor: 'rgba(127,0,0,0.3)',
    padding: Spacing.md,
  },
  errorBannerText: {
    color: '#fca5a5',
    fontSize: Typography.fontSize.sm,
    textAlign: 'center',
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: Spacing.sm,
    padding: Spacing.md,
    borderTopWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(19,40,30,0.95)',
  },
  chatInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    borderRadius: Radius.xxl - 2,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm + 2,
    fontSize: Typography.fontSize.base,
    color: Colors.textPrimary,
    backgroundColor: 'rgba(23,49,35,0.9)',
    maxHeight: 100,
  },
  micBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    backgroundColor: 'rgba(23,49,35,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  micBtnText: {
    fontSize: Typography.fontSize.xl,
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: {
    opacity: 0.4,
  },
  sendBtnText: {
    color: '#102419',
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.lg,
  },
  voiceOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.75)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceCard: {
    width: 260,
    height: 260,
    borderRadius: Radius.xxl,
    backgroundColor: 'rgba(11,27,19,0.97)',
    borderWidth: 1,
    borderColor: 'rgba(52,211,153,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.md,
  },
  voiceCloseBtn: {
    position: 'absolute',
    top: Spacing.base,
    right: Spacing.base,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255,255,255,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceCloseText: {
    color: Colors.textMuted,
    fontSize: Typography.fontSize.base,
  },
  voiceOrb: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(16,185,129,0.2)',
    borderWidth: 2,
    borderColor: 'rgba(52,211,153,0.6)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceOrbText: {
    fontSize: Typography.fontSize.h1 + 2,
  },
  voiceListeningText: {
    fontSize: Typography.fontSize.lg,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
  },
  voiceSubText: {
    fontSize: Typography.fontSize.sm,
    color: Colors.textMuted,
  },
  stopVoiceBtn: {
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.lg,
    backgroundColor: 'rgba(239,68,68,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(239,68,68,0.5)',
  },
  stopVoiceText: {
    color: '#fca5a5',
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
  },
});
