import { StyleSheet } from 'react-native';
import { Colors } from '../../theme/colors';
import { Typography } from '../../theme/typography';
import { Spacing, Radius } from '../../theme/spacing';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bg,
  },
  hero: {
    paddingTop: 80,
    paddingBottom: 50,
    paddingHorizontal: Spacing.xxl,
    alignItems: 'center',
  },
  heroBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: 'rgba(201,138,60,0.5)',
    backgroundColor: 'rgba(201,138,60,0.16)',
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.md + 2,
    paddingVertical: Spacing.sm - 1,
    marginBottom: Spacing.xxl,
  },
  pulseDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Colors.gold,
  },
  heroBadgeText: {
    color: Colors.textPrimary,
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.medium,
  },
  heroTitle: {
    fontSize: Typography.fontSize.display - 2,
    fontWeight: Typography.fontWeight.extraBold,
    color: '#fff',
    textAlign: 'center',
    lineHeight: 44,
    letterSpacing: Typography.letterSpacing.tight,
    marginBottom: Spacing.lg,
  },
  heroSubtitle: {
    fontSize: Typography.fontSize.xl - 1,
    color: 'rgba(244,239,228,0.75)',
    textAlign: 'center',
    marginBottom: Spacing.xxxl,
  },
  heroButtons: {
    flexDirection: 'column',
    gap: Spacing.md,
    width: '100%',
    marginBottom: Spacing.xl,
  },
  btnGold: {
    backgroundColor: Colors.gold,
    borderRadius: Radius.md,
    paddingVertical: Spacing.md + 3,
    alignItems: 'center',
    width: '100%',
  },
  btnGoldText: {
    color: '#1B1204',
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.bold,
  },
  btnOutline: {
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.55)',
    borderRadius: Radius.md,
    paddingVertical: Spacing.md + 3,
    alignItems: 'center',
    width: '100%',
  },
  btnOutlineText: {
    color: '#fff',
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.semiBold,
  },
  govtBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.xxl,
    borderWidth: 1,
    borderColor: 'rgba(74,222,128,0.45)',
    backgroundColor: 'rgba(74,222,128,0.08)',
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.xl - 2,
    paddingVertical: Spacing.sm + 1,
  },
  govtDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#4ade80',
  },
  govtBadgeText: {
    color: '#4ade80',
    fontSize: Typography.fontSize.base - 1,
    fontWeight: Typography.fontWeight.semiBold,
  },
  emergencyCall: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  emergencyCallText: {
    color: Colors.textPrimary,
    fontSize: Typography.fontSize.base,
  },
  emergencyCallNumber: {
    color: '#fff',
    fontWeight: Typography.fontWeight.bold,
    fontSize: Typography.fontSize.base,
    borderBottomWidth: 1,
    borderColor: Colors.gold,
  },
  section: {
    padding: Spacing.xxl,
    backgroundColor: 'rgba(244,239,228,0.04)',
  },
  sectionLabel: {
    fontSize: Typography.fontSize.sm,
    fontWeight: Typography.fontWeight.bold,
    color: '#A9734A',
    marginBottom: Spacing.sm,
    letterSpacing: Typography.letterSpacing.wide,
  },
  sectionTitle: {
    fontSize: Typography.fontSize.h3,
    fontWeight: Typography.fontWeight.extraBold,
    color: '#1C3A2C',
    lineHeight: 30,
    marginBottom: Spacing.md + 2,
  },
  sectionBody: {
    fontSize: Typography.fontSize.md,
    color: '#3E4B41',
    lineHeight: 23,
  },
  statsContainer: {
    marginTop: Spacing.xl,
    borderRadius: Radius.lg - 2,
    overflow: 'hidden',
  },
  statRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1C3A2C',
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.xl,
  },
  statRowFirst: {
    borderTopLeftRadius: Radius.lg - 2,
    borderTopRightRadius: Radius.lg - 2,
  },
  statRowLast: {
    borderBottomLeftRadius: Radius.lg - 2,
    borderBottomRightRadius: Radius.lg - 2,
  },
  statNum: {
    fontSize: Typography.fontSize.h2 - 2,
    fontWeight: Typography.fontWeight.extraBold,
    color: Colors.gold,
  },
  statLabel: {
    fontSize: Typography.fontSize.base - 1,
    color: '#8AA68F',
    textAlign: 'right',
    maxWidth: 180,
  },
  stepsGrid: {
    gap: Spacing.md,
    marginTop: Spacing.lg,
  },
  stepCard: {
    backgroundColor: '#1C3A2C',
    borderRadius: Radius.lg,
    padding: Spacing.xl,
  },
  stepNum: {
    fontSize: Typography.fontSize.base - 1,
    fontWeight: Typography.fontWeight.extraBold,
    color: Colors.gold,
    marginBottom: Spacing.sm,
  },
  stepTitle: {
    fontSize: Typography.fontSize.lg + 1,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
    marginBottom: Spacing.xs + 2,
  },
  stepCopy: {
    fontSize: Typography.fontSize.base - 1,
    color: '#8AA68F',
    lineHeight: 20,
  },
  tipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.md + 2,
    backgroundColor: '#fff',
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(21,32,24,0.12)',
    padding: Spacing.xl - 2,
    marginBottom: Spacing.md,
  },
  tipIcon: {
    width: 40,
    height: 40,
    borderRadius: Radius.md - 2,
    backgroundColor: 'rgba(169,113,74,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tipIconText: {
    fontSize: Typography.fontSize.xl,
    color: '#A9734A',
  },
  tipTitle: {
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.bold,
    color: '#1C3A2C',
    marginBottom: Spacing.xs,
  },
  tipCopy: {
    fontSize: Typography.fontSize.base - 1,
    color: '#4A564D',
    lineHeight: 20,
  },
  emergencyBanner: {
    padding: Spacing.xxl + 4,
    gap: Spacing.lg,
  },
  emergencyBannerTitle: {
    fontSize: Typography.fontSize.xxl,
    fontWeight: Typography.fontWeight.extraBold,
    color: '#fff',
    lineHeight: 30,
    flex: 1,
  },
  emergencyBannerLabel: {
    fontSize: Typography.fontSize.base - 1,
    color: 'rgba(255,255,255,0.75)',
    marginBottom: Spacing.xs,
  },
  emergencyBannerNumber: {
    fontSize: Typography.fontSize.h1 - 2,
    fontWeight: Typography.fontWeight.extraBold,
    color: '#fff',
  },
  footer: {
    backgroundColor: '#0D2119',
    padding: Spacing.xxl + 4,
    paddingBottom: Spacing.huge + 8,
  },
  footerBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  footerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.gold,
  },
  footerBrandText: {
    fontSize: Typography.fontSize.md,
    fontWeight: Typography.fontWeight.bold,
    color: Colors.textPrimary,
  },
  footerDesc: {
    fontSize: Typography.fontSize.base - 1,
    color: '#8AA68F',
    lineHeight: 20,
    marginBottom: Spacing.xl,
  },
  footerCopy: {
    fontSize: Typography.fontSize.sm,
    color: 'rgba(138,166,143,0.8)',
    lineHeight: 18,
  },
});
